//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienDoDA
    {
        public int MaTD { get; set; }
        public string MaDA { get; set; }
        public string CongViec { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual DuAn DuAn { get; set; }
    }
}
