//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VatTu()
        {
            this.VatTuTrongDuAns = new HashSet<VatTuTrongDuAn>();
        }
    
        public int MaVT { get; set; }
        public string TenVT { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string ĐonViTinh { get; set; }
        public Nullable<int> MaNCC { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VatTuTrongDuAn> VatTuTrongDuAns { get; set; }
    }
}
